### ISSUE TITLE
hierarchy in non standard codes

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [FINNGEN/ETL#165]
- [x] add columns to vocabularies in https://github.com/FinOMOP/FinOMOP_OMOP_vocabulary/issues/63
- [x] add code to https://github.com/FinOMOP/ROMOPMappingTools/issues/7
- [x] create hades flavor script to create `concept_ancestor` table based on `concept_relationsip` https://github.com/FINNGEN/ETL/issues/172
- [ ] https://github.com/FINNGEN/ETL/issues/184
